# ClockScreenlet - "Plain-Clock-Roman-Numerals"-theme 

[Theme]
name	= Plain Clock Roman Numerals
author	= patxiherran
version	= 1.0
info	=  Based in Plain Clock 0.1 from xasthur (all but numerals) and Street clock from Palko (the numerals from clock-marks.svg -and 4 as IIII-)
http://gnome-look.org/content/show.php?action=content&content=58984
http://gnome-look.org/content/show.php?action=content&content=158623

